### PR TITLE
Added master link to download all songs at one time

### PR DESCRIPTION
**Pull request by skotz**
Added a link to the main H1 header to download all links on the page at once. Chrome security requires that the user allow "multiple downloads" on the page the first time this feature is used.

### CODE REVIEW

**Comment by fzakaria** [comment]
Neat.
I'll try to install and give it a go.
What would be cool would be just a checkbox (with select All/None option) and then to download all checkbox'd songs.

**Comment by skotz** [comment]
That should be a relatively simple adjustment to make. I'll try to take a look tomorrow evening.

**Comment by skotz** [comment]
Is this more what you were looking for? Let me know if you need commits squashed.

image

**Comment by fzakaria** [comment]
Yea I think that would be sweet.


Farid Zakaria

**Comment by fzakaria** [comment]
A good merge commit will suffice.

Farid Zakaria

**Comment by pulverize** [comment]
Beautiful. Good man.

**Comment by fzakaria** [comment]
checked it out. epic.

**Comment by jhelmink** [comment]
Loved this by that way. Thanks guys,

**Comment by fzakaria** [comment]
Yes. Very good PR.
Shame that rename bug can't be fixed :(

**Comment by robobeirne** [comment]
Any chance of changing where it appears as on the favourites page the download button appears under the sort by button so can't be clicked.
capture

**Comment by dideler** [comment]
When I have [uBlock origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) enabled, I either don't have the download options in the page's submenu

image

or it appears at the wrong location.

image

Disabling uBlock for the site makes the download options appear correctly.

image

This probably because the last item in the `submenu` (before`DownloadAllSection` is appended) is a twitter item. Blocking it interferes with the download options.

Also, could the version number please be bumped with the addition of this new feature?

**Pull request merged**
